ARG BASE_IMAGE_LABEL
FROM toposoid/python-nlp-english:${BASE_IMAGE_LABEL}

ARG TARGET_BRANCH
ARG SENTENCE_TRANSFORMER_MODEL
ARG PIPELINES_MODEL

WORKDIR /app
ENV DEPLOYMENT=local

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
&& apt-get -y install git unzip \
&& curl -LsSf https://astral.sh/uv/install.sh | sh \
&& source ${HOME}/.local/bin/env \
&& git clone https://github.com/toposoid/toposoid-common-nlp-english-web.git \
&& cd toposoid-common-nlp-english-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& mkdir -p models \
&& mkdir -p models/sentence-transformers_${SENTENCE_TRANSFORMER_MODEL} \
&& mv -f /tmp/${SENTENCE_TRANSFORMER_MODEL}/* ./models/sentence-transformers_${SENTENCE_TRANSFORMER_MODEL}/ \
&& rm -Rf /tmp/*
&& uv sync \
&& uv add git+https://github.com/toposoid/toposoid-python-lib.git@${TARGET_BRANCH}#egg=ToposoidCommon \
&& uv run installWordNet.py \
&& uv run -- spacy download ${PIPELINES_MODEL}

#&& sed -i s/__##GIT_BRANCH##__/${TARGET_BRANCH}/g requirements.txt \
#&& pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt \
